name: golder_octopus
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  # Logic
  dartz: ^0.10.1
  equatable: ^2.0.5
  catcher_2: ^2.1.3
  

  # State Managment
  flutter_bloc: ^8.1.3
  bloc: ^8.1.4

  # DI 
  injectable: ^2.5.0
  get_it: ^8.0.3


  # Networking & API
  dio: ^5.3.0
  pretty_dio_logger: ^1.4.0
  device_info_plus: ^11.5.0
  local_auth: ^2.3.0
  url_launcher: ^6.3.1

  # UI
  google_fonts: ^6.2.1
  text_scroll: ^0.2.0
  toastification: ^3.0.2
  cached_network_image: ^3.4.1
  easy_localization: ^3.0.7+1
  fl_chart: ^1.0.0
  camera: ^0.11.1
  permission_handler: ^12.0.1
  image_picker: ^1.1.2
  flutter_svg: ^2.2.0
  flutter_gen: ^5.10.0
  dropdown_search: ^6.0.2
  intl: ^0.20.2
  share_plus: ^11.0.0
  path_provider: ^2.1.5
  image_gallery_saver_plus: ^4.0.1
  hive_ce: ^2.11.3
  hive_ce_flutter: ^2.3.1
  hive_ce_generator: ^1.9.2
  pdf: ^3.11.3
  printing: ^5.14.2
  skeletonizer: ^2.1.0+1
  data_table_2: ^2.6.0
  mobile_scanner: ^7.0.1
  google_mlkit_barcode_scanning: ^0.14.1
  # awesome_dialog: ^3.2.1
  


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  build_runner: ^2.4.13
  flutter_gen_runner: ^5.8.0
  injectable_generator: ^2.7.0


flutter_gen:
  output: lib/generated/




flutter:

  uses-material-design: true

  assets:
    - assets/translations/
    - assets/images/
    - assets/images/navbar/
    - assets/images/logo/
    - assets/images/flags/
    - assets/images/quick_actions/
    - assets/images/side_actions/

  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package


