// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive.dart';
import 'package:golder_octopus/core/local_models/hive_adapters.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(CurAdapter());
    registerAdapter(CurrenciesResponseAdapter());
    registerAdapter(LoginParamsAdapter());
    registerAdapter(LoginResponseModelAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(CurAdapter());
    registerAdapter(CurrenciesResponseAdapter());
    registerAdapter(LoginParamsAdapter());
    registerAdapter(LoginResponseModelAdapter());
  }
}
